name: CI

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: laravel_tags
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: connect to database
        run: apt-get -y install wait-for-it

      - name: connect to database
        run: wait-for-it 172.17.0.1:3306

      - name: Build App Image
        run: docker build --file ./devops/Dockerfile --tag jeroenboesten/database-test:foobar .
