name: CI

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: [ubuntu-latest]
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: testing
          MYSQL_PASSWORD: testing
          MYSQL_DATABASE: laravel_tags
        ports:
          - 3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: connect
        run: mysql -h 127.0.0.1 --port ${{ job.services.mysql.ports[3306] }} -u testing -p=testing

      - name: Build App Image
        run: docker build --file ./devops/Dockerfile --build-arg MYSQL_PORT=${{ job.services.mysql.ports[3306] }} --tag jeroenboesten/database-test:foobar .
